---
title: "report1"
author: "Nathaniel Brown, Huijia Yu, Angie Shen"
date: "November 6, 2017"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message=FALSE)
library(reshape2)
library(ggplot2)
library(dplyr)
```

# Introduction

blah blah blah malaria.

# Exploratory Data Analysis

```{r}
dat <- read.csv("gambiaMissing.csv")

bednet_group <- function(dat= NA, predictor = NA){
  bednet_group <- dat %>% 
                group_by_(predictor) %>% 
                summarize(BEDNET0 = mean(BEDNET==0 & !is.na(BEDNET)), 
                          BEDNET1 = mean(BEDNET==1 & !is.na(BEDNET)), 
                          BEDNETNA = mean(is.na(BEDNET))) %>%
                melt(id=predictor)
  return(bednet_group)
}

bednet_age <- bednet_group(dat, "AGE")
bednet_green <- bednet_group(dat, "GREEN")
bednet_phc <- bednet_group(dat, "PHC")
bednet_y <- bednet_group(dat, "Y")

ggplot(data=bednet_age, aes(x=as.factor(AGE), y=value, fill=variable)) + geom_col(position="dodge")
ggplot(data=bednet_green, aes(x=as.factor(GREEN), y=value+1E-10, fill=variable)) + geom_col(position="dodge")
ggplot(data=bednet_phc, aes(x=as.factor(PHC), y=value, fill=variable)) + geom_col(position="dodge")
ggplot(data=bednet_y, aes(x=as.factor(Y), y=value, fill=variable)) + geom_col(position="dodge")
```

# Test for Missingness Mechanism

glm goes here

# Discussion of Approaches

blah blah blah

# Contributions

blah

<!--
Mice stuff 

 ```{r}
 data <- read.table("kellydat.txt", header=T)
 data$race = 0
 data$race[data$black==1|data$hisp==1] = 1
 data$sn0 = 0
 data$sn0[data$sn1==0 & data$sn2==0 & data$sn3==0 & data$all4==0] = 1
 
 data.imp = data
 data.imp$nctdel[data.imp$fail == 0] = NA
 
 #md.pattern(data.imp[!is.na(data.imp$nctdel),])
 
 tempData <- mice(data.imp,m=5,maxit=50,meth='pmm',seed=500, print=FALSE)
 # methods: 
 # 2l.norm / 2l.pan / 2lonly.mean / 2lonly.norm / 2lonly.pmm / 
 # cart / fastpmm / lda / logreg / logreg.boot / mean / midastouch / norm / norm.boot / norm.nob / 
 # norm.predict / passive / pmm / polr / polyreg / quadratic / rf / ri / sample
 
 #tempData$imp$nctdel
 
 data.imp <- complete(tempData)
 
 hist(log(data.imp$nctdel + 0.1))
 
 fit <-lm(log(nctdel+0.1) ~ sn0 + sn1 + sn2 + race + male, data = data)
 ```
 
 ##Diagnostic 
 
 
 
 
 
 
 
 ```{r}
 library(VIM)
 library(mice)
 
 
 ##looking for pattern of missing data
 md.pattern(data.imp)
 
 #visualizations: 
 aggr_plot <- aggr(data, col=c('navyblue','red'), numbers=TRUE, sortVars=TRUE, labels=names(data), cex.axis=.7, gap=3, ylab=c("Histogram of missing data","Pattern"))
 
 marginplot(data.imp[c(1,2)])
 marginplot(data[c(1,3)])
 marginplot(data[c(1,4)])
 marginplot(data[c(1,5)])
 marginplot(data[c(1,6)])
 marginplot(data[c(1,7)])
 marginplot(data[c(1,8)])
 marginplot(data[c(1,9)])
 marginplot(data[c(1,10)])
 
 
 
 #visualize distribution of original and imputed data- check if imputed data is lausible
 
 #xyplot(tempData,nctdel ~ fail+male+black,pch=18,cex=1)  
 
 #densityplot(tempData)
 
#stripplot(data, pch = 20, cex = 1.2)
```
-->